### ISSUE TITLE
Ошибка: FATAL:  data directory "/var/lib/postgresql/data" has invalid permissions при запуске контейнера

### ISSUE THREAD

**Issue by camenzindmp** [camenzindmp/PostgreSQL#1]
## Описание:
При запуске контейнера возникает ошибка `FATAL:  data directory "/var/lib/postgresql/data" has invalid permissions`

## Скриншот: 
![log](https://user-images.githubusercontent.com/59551106/103454715-787b9280-4d32-11eb-9cb7-eaeba95936a4.png)

## Воспроизведение:
1. Скачать проект
2. Запустить контейнер командой `docker-compose up`

## Ожидаемый результат:
Контейнер запускается корректно. Ошибок не возникает

## Фактический результат:
Возникает ошибка  `FATAL:  data directory "/var/lib/postgresql/data" has invalid permissions`

## Окружение:
Win10x64 PRO

**Comment by andrew-pahomov** [comment]
Добрый день.                     
Описанная Вами проблема известна разработчикам. Возникает при использовании томов с контейнером postgresql под Windows. Чтобы избежать появление сообщений об ошибке можно попробовать выполнить настройку с использованием постоянного внешнего тома.                 
```
version: '3.7'
services:
  postgresql:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_USER=postgresql_admin
      - POSTGRES_DB=postgresql

volumes:
  pgdata:
    external: true
```
